enhanced iptenrule - better notes and error handling

diff --git a/usr/bin/iptenrule b/usr/bin/iptenrule
--- a/usr/bin/iptenrule
+++ b/usr/bin/iptenrule
@@ -15,6 +15,19 @@ if ! [ -e "$A_PATH/$1" ]; then
 fi;
 
 # Print out the comments in case other action needs to be taken
-grep -P '^#' "$A_PATH/$1"|sed 's/^#/^/';
+if [ "$(grep -P '^#' $A_PATH/$1|wc -l)" != 0 ]; then
+  echo "";
+  echo "Notes from $1 rules:";
+  grep -P '^#' "$A_PATH/$1"|sed 's/^# /* /';
+  echo "";
+fi;
 
 ln -s "$A_PATH/$1" "$E_PATH/$1";
+
+if [ "$?" != "0" ]; then
+  echo "Unable to enable $1 rules";
+  exit 1;
+fi;
+
+echo "$1 rules enabled";
+echo "Don't forget to run 'ipt -i' to install the rules";
